ktor:
    application:
        modules:
            - ru.mirea.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: postgres
  password: postgres
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
