ktor:
    application:
        modules:
            - ru.mirea.ApplicationKt.module
    deployment:
        port: 8080
postgres:
    url: "$DATABASE_URL:jdbc:postgresql://localhost:5434/postgres"
    user: "$DATABASE_USERNAME:postgres"
    password: "$DATABASE_PASSWORD:postgres"
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
